[package]
name = "flux"
version = "0.1.0"
authors = ["PZ Read"]

[dependencies]
dotenv = "0.10"
futures = "0.1"
hyper = { git = "https://github.com/pzread/hyper" }
lazy_static = "0.2"
regex = "0.2"
rustc-serialize = "0.3"
tokio-core = "0.1"
uuid = { version = "0.4", features = ["v4"] }
