[package]
name = "furakus"
version = "0.0.1"
authors = ["PZ Read <netfirewall@gmail.com>"]
license = "MIT"
repository = "https://github.com/pzread/furakus"

[badges]
travis-ci = { repository = "pzread/furakus" }
appveyor = { repository = "pzread/furakus" }

[dependencies]
bytes = "0.4"
dotenv = "0.10"
futures = "0.1"
hyper = { git = "https://github.com/hyperium/hyper" }
language-tags = "0.2"
lazy_static = "0.2"
mime = "0.3"
regex = "0.2"
ring = "0.12"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio-core = "0.1"
url = "1.5"
uuid = { version = "0.5", features = ["v4"] }
