[package]
name = "furakus-next"
version = "0.1.0"
authors = ["PZ Read"]
edition = "2018"

[dependencies]
futures-preview = { version = "=0.3.0-alpha.16", features = ["async-await", "compat", "nightly"] }
hyper = "0.12"
lazy_static = "1"
regex = "1"
tokio = "0.1"
url = "1"
