[package]
name = "flux"
version = "0.1.0"
authors = ["PZ Read"]

[dependencies]
dotenv = "0.10"
futures = "0.1"
hyper = { git = "https://github.com/pzread/hyper", branch = "expect" }
lazy_static = "0.2"
mime = "0.2"
regex = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio-core = "0.1"
uuid = { version = "0.4", features = ["v4"] }
